### ISSUE TITLE
Unexpected error processing resource type AWS::Lambda::Permission

### ISSUE THREAD

**Issue by subvertallchris** [localstack/localstack-demo#50]
Hello! I'm trying to run this demo and I receive two of the following errors on deploy:

```
l.s.c.e.template_deployer  : Unexpected error processing resource type AWS::Lambda::Permission: Exception: Parameter validation failed:
Invalid type for parameter FunctionName, value: {'Fn::GetAtt': ['HttpHandleRequestLambdaFunction', 'Arn']}, type: <class 'dict'>, valid types: <class 'str'> - {'FunctionName': {'Fn::GetAtt': ['HttpHandleRequestLambdaFunction', 'Arn']}, 'Action': 'lambda:InvokeFunction', 'Principal': 'apigateway.amazonaws.com', 'SourceArn': {'Fn::Join': ['', ['arn:', {'Ref': 'AWS::Partition'}, ':execute-api:', {'Ref': 'AWS::Region'}, ':', {'Ref': 'AWS::AccountId'}, ':', {'Ref': 'ApiGatewayRestApi'}, '/*/*']]}} - status: None
```

I'm seeing this same error when I try to create a new Localstack project. After banging my head against it for a while, I figured I'd try the demo to see if it was just me and... here we are!

Is there a particular version of a dependency that I should be using? Some underlying configuration that I missed?

Thank you!

**Comment by whummer** [comment]
Thanks for reporting @subvertallchris . Can you please share the version of LocalStack you're using (please share the output of `docker images`) - does the problem persist after pulling the `latest` image? Thanks

**Comment by subvertallchris** [comment]
Hey, thanks for checking in. You were right, updating everything seemed to
resolve it. I should have tried that first. Thank you!
