### ISSUE TITLE
Parsing fails as default output is yml 

### ISSUE THREAD

**Issue by mrudulp** [localstack/localstack-demo#54]
This fails as default output of command `awslocal apigateway get-rest-apis` is yml and not json.
Using `apiId=$$(awslocal apigateway get-rest-apis --output json | jq -r '.items[] | select(.name="local-localstack-demo") | .id'); \`
instead of this
https://github.com/localstack/localstack-demo/blob/1c81a708da8a0271db1ea4c88fb9be1570c4231c/Makefile#L20
ensures install goes through.

Other notes about demo instructions --
jq installation should be checked on system or be part of install

**Comment by lakkeger** [comment]
Hi @mrudulp,
Closing this issue now as it fixes the proposed issues. However please do not hesitate to contact us if you have any further questions or encounter new issues, even if everything is working now. Thank you.
